spring:
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 388410756179-8geald8f2og9k3b3op7ndkvfd375u8vk.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: https://ewkrqwjrqwerkqwerkq3erq.ru/login/oauth2/code/google
            user-name-attribute: name
          vk:
            client-id: 51814557
            client-secret: XR7QUPBH9mnnDWpUOKcp
            redirect-uri: https://ewkrqwjrqwerkqwerkq3erq.ru/login/oauth2/code/vk
            user-name-attribute: first_name
  fatum:
    api:
      url: http://87.242.94.128:8090/predict

